### ISSUE TITLE
游戏服务器重启后无法启动进程

### ISSUE THREAD

**Issue by ximenlumao** [Verthandii/palworld-go#7]
服务器在首次执行脚本后如果游戏没有启动，可以正常启动进程
 【Supervisor】启动成功，开始守护游戏进程
2024/01/29 17:53:37 【Memory】启动成功，定时清理服务器内存
2024/01/29 17:53:37 【Supervisor】健康检查失败【exit status 1】
2024/01/29 17:53:37 【Supervisor】正在尝试重新启动服务器
2024/01/29 17:53:37 【Supervisor】服务器启动成功

但是我遇到的问题是服务器自动重启后，在启动的时候 无法启动帕鲁进程
2024/01/29 17:54:57 【Supervisor】服务器即将重启, 重新设置轮询周期, 避免长时间等待服务器重
2024/01/29 17:56:07 【Supervisor】ALIVE
2024/01/29 17:56:17 【Supervisor】ALIVE

虽然程序判断已激活状态，但是进程就是没有启动
使用的steam用户执行的

**Comment by Verthandii** [comment]
linux环境下没有做过多测试，如果实在不行，麻烦先使用root用户使用。子用户的情况请等待后续修复。

**Comment by Verthandii** [comment]
**已解决**
BUG原因：父进程未等待子进程退出，未释放子进程资源，导致 Supervisor 认为服务器依然存活，未进行重启。
