### ISSUE TITLE
Linux 下的内存检测问题

### ISSUE THREAD

**Issue by ench233** [Verthandii/palworld-go#9]
![image](https://github.com/Verthandii/palworld-go/assets/79665752/24bd484e-119d-46b3-8268-a89844cc7134)
![image](https://github.com/Verthandii/palworld-go/assets/79665752/a9715aa4-5fed-4d18-9c48-ef32e195d0f4)
如果这样检测在中文环境的Linux系统会出问题

**Comment by Verthandii** [comment]
done
